import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { BookmarkProvider } from "../components/BookmarkContext";
import { SearchProvider } from "../components/SearchContext";
//components
import Navbar from "../components/Navbar";
import Search from "../components/Search";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "500"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <BookmarkProvider>
          <SearchProvider>
            <div className="flex justify-center">
              <div className="w-full max-w-screen-2xl flex">
                <div className="w-44">
                  <div className="fixed">
                    <Navbar />
                  </div>
                </div>
                <div className="mt-12 w-[1240px]">
                  <Search />
                  <div>{children}</div>
                </div>
              </div>
            </div>
          </SearchProvider>
        </BookmarkProvider>
      </body>
    </html>
  );
}
