import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//components
import Navbar from "../components/Navbar";
import Search from "../components/Search";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex">
          <Navbar />
          <div className="mt-12">
            <Search />
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
